name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy on gh-pages
      run: |  
        set -e
        yarn install
        yarn build
        cd dist
        git config user.email "marco.cilona@gmail.com"
        git config user.name "MarcoCilona"
        git init
        git add -A
        git commit -m 'deploy'
        git push -f https://github.com/MarcoCilona/http-analyzer.git master:gh-pages

